# Generated by Django 5.2.5 on 2025-08-25 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('consumo_alto', 'Consumo Alto'), ('dispositivo_offline', 'Dispositivo Offline'), ('limite_zona', 'Límite de Zona Superado')], max_length=20)),
                ('mensaje', models.TextField()),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítico')], max_length=10)),
                ('fecha_alerta', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada')], default='activa', max_length=15)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='dispositivos.dispositivo')),
            ],
            options={
                'ordering': ['-fecha_alerta'],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_kwh', models.DecimalField(decimal_places=3, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='dispositivos.dispositivo')),
            ],
            options={
                'verbose_name_plural': 'Mediciones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
